### ISSUE TITLE
Set up a release pipeline

### ISSUE THREAD

**Issue by GSGBen** [GSGBen/t2md#12]
As part of this, release the previous changes.

## TODO

- [x] test a push to a pull request, make sure it doesn't trigger a publish (if statement)
  - confirmed
- [x] test another push after the current action updates the tag. If it fails again change to a different one which doesn't clobber tags
  - It's clobbering. Replace.
  - changed to a manual trigger and manual tag.
- [x] test which version of the workflow file runs on a branch - the new branch one or main?
  - [x] as me
    - runs the changed workflow from the branch
  - [x] as someone else with a pull-request
    - runs their workflow, but with enhanced security: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/. No access to secrets, and can't read from the API using GITHUB_TOKEN
    - would be the same for tests. 
  - https://blog.gitguardian.com/github-actions-security-cheat-sheet/
