### ISSUE TITLE
Add an option to remove emoji in titles and paths

### ISSUE THREAD

**Issue by GSGBen** [GSGBen/t2md#9]
Dropbox doesn't support emoji in filenames.

- card titles
- list folders
- board folders

For lists:

Create a `GetUsableListName()` like `GetUsableCardName()` but without the length limiting, then make sure to use it in `GetDuplicateNameKey()` too.

## TODO

- [x] add the option
- [x] create a function to remove emoji
- [x] add a test
- [x] pass the option through and use it in `GetUsableCardName()`
- [x] create a `GetUsableListName()` and use it there
- [x] cast and reference `GetUsableListName()` in `GetDuplicateNameKey()`
- [x] add a test to ensure duplicates are incremented when enabled
- [x] remove from the board name if only used in one place
  - Exception. The code is leaving a space at the end of a folder, but the delete function trims and fails. Trim in this issue/branch.
    - Note: the fix to remove this (from [here](https://answers.microsoft.com/en-us/windows/forum/all/remove-a-folder-with-space-at-the-end/2db209ad-9e82-41dd-b05b-4ed681845aa9) is to delete via the short name. Use `dir /X` to see it.
- [x] Trim trailing and preceding whitespace, and multiple spaces within card, list and board titles
 - [x] close #26
